### ISSUE TITLE
Inconsistent declaration of Query

### ISSUE THREAD

**Issue by twibster** [aravindnc/mongoose-paginate-v2#220]
**Describe the bug**
On the latest version of mongoose (8.6.3), There is a difference in `RawDocType` parameter type (`unknown`) in the Query class in mongoose.d.ts:
```ts
class Query<ResultType, DocType, THelpers = {}, RawDocType = unknown, QueryOp = 'find', TInstanceMethods = Record<string, never>>
```
and Query interface in index.d.ts (Ref to `DocType`) from the package here:
```ts
interface Query<ResultType, DocType, THelpers = NonNullable<unknown>, RawDocType = DocType, QueryOp = 'find', TInstanceMethods = Record<string, never>>
```
which is causing an inconsistent declaration error in TypeScript

**To Reproduce**
1- building the application or whatever using the package and mongoose

**Expected behavior**
A matching declaration of Query in the package and in mongoose

**Comment by twibster** [comment]
A solution to this problem is replacing the type parameter for `RawDocType` from `DocType` to `unkown` to match mongoose Query declaration
```ts
interface Query<
    ResultType,
    DocType,
    THelpers = NonNullable<unknown>,
    RawDocType = unknown,
    QueryOp = 'find',
    TInstanceMethods = Record<string, never>,
  > {
    paginate<O extends PaginateOptions>(
      options?: O
    ): Promise<PaginateResult<PaginateDocument<RawDocType, TInstanceMethods, O>>>
    paginate<UserType = ResultType, O extends PaginateOptions = PaginateOptions>(
      options?: O
    ): Promise<PaginateResult<PaginateDocument<UserType, TInstanceMethods, O>>>
    paginate<UserType = ResultType>(
      options?: PaginateOptions
    ): Promise<PaginateResult<PaginateDocument<UserType, TInstanceMethods, PaginateOptions>>>
  }
```

**Comment by twibster** [comment]
also we can simply ignore the error by placing the following line before the interface:
```
// @ts-expect-error overwriting of mongoose Query interface
```
as in:

```
// @ts-expect-error overwriting of mongoose Query interface
  interface Query<
    ResultType,
    DocType,
    THelpers = NonNullable<unknown>,
    RawDocType = DocType,
    QueryOp = 'find',
    TInstanceMethods = Record<string, never>,
  > {
    paginate<O extends PaginateOptions>(
      options?: O
    ): Promise<PaginateResult<PaginateDocument<RawDocType, TInstanceMethods, O>>>
    paginate<UserType = ResultType, O extends PaginateOptions = PaginateOptions>(
      options?: O
    ): Promise<PaginateResult<PaginateDocument<UserType, TInstanceMethods, O>>>
    paginate<UserType = ResultType>(
      options?: PaginateOptions
    ): Promise<PaginateResult<PaginateDocument<UserType, TInstanceMethods, PaginateOptions>>>
  }
```

**Comment by aravindnc** [comment]
Thanks for the fix. @twibster

**Comment by Clashsoft** [comment]
This is still not fixed as of 1.9.0. The @ts-ignore commit does not work because the error still shows in the mongoose declaration:

```ts
node_modules/.pnpm/mongoose@8.9.3/node_modules/mongoose/types/query.d.ts:241:9 - error TS2428: All declarations of 'Query' must have identical type parameters.

241   class Query<ResultType, DocType, THelpers = {}, RawDocType = unknown, QueryOp = 'find', TDocOverrides = Record<string, never>> implements SessionOperation {
            ~~~~~

```

**Comment by aravindnc** [comment]
@Clashsoft Please see if it works with v1.8.5

**Comment by Clashsoft** [comment]
Nope.
```
node_modules/.pnpm/mongoose-paginate-v2@1.8.5/node_modules/mongoose-paginate-v2/index.d.ts:132:13 - error TS2428: All declarations of 'Query' must have identical type parameters.

132   interface Query<
                ~~~~~

node_modules/.pnpm/mongoose@8.9.3/node_modules/mongoose/types/query.d.ts:241:9 - error TS2428: All declarations of 'Query' must have identical type parameters.

241   class Query<
            ~~~~~

```

mongoose-paginate-v2
```
  interface Query<
    ResultType,
    DocType,
    THelpers = NonNullable<unknown>,
    RawDocType = DocType,
    QueryOp = 'find',
    TInstanceMethods = Record<string, never>,
  > {
```

mongoose
```
  class Query<
    ResultType,
    DocType,
    THelpers = {},
    RawDocType = unknown,
    QueryOp = 'find',
    TDocOverrides = Record<string, never>
  > implements SessionOperation {
```

**Comment by eldhoseelias** [comment]
@aravindnc This issue is not resolved yet. Issue still exists in 1.8.5 and 1.9.0
